version: '3.8'

services:
  db:
    restart: always
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=university
#      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  app:
    build: ./
    container_name: timetable-app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/university
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
#volumes:
#  pgdata: {}
