spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5432/university
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.format_sql: true